[project]
name = "etl-runner"
version = "0.1.0"
description = "ETL Runner"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-bigquery>=3.31.0",
    "pandas>=2.2.3",
    "pyyaml>=6.0.2",
]
